url: "https://codigo.atriomarketing.site"
title: "Código VGV"

plugins:
  - jekyll-sitemap

exclude:
  - vgv47/
  - "*.pdf"
  - README.md

defaults:
  - scope:
      path: "vgv47"
    values:
      sitemap: false
